name: Docker CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-inference:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-inference:latest

    - name: SSH into EC2 and update container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-inference:latest
          docker stop inference || true
          docker rm inference || true
          docker run -d --name inference -p 80:8000 ${{ secrets.DOCKER_USERNAME }}/fastapi-inference:latest
